#if !canImport(ObjectiveC)
import XCTest

extension DateFromPathTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DateFromPathTests = [
        ("testBasics", testBasics),
    ]
}

extension DatePathFragmentTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DatePathFragmentTests = [
        ("testBasics", testBasics),
    ]
}

extension DatePrefixTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DatePrefixTests = [
        ("testDatePrefix", testDatePrefix),
    ]
}

extension DraftTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DraftTests = [
        ("testDraft", testDraft),
        ("testMissingDraftIsNotConsideredDraft", testMissingDraftIsNotConsideredDraft),
        ("testNotDraft", testNotDraft),
        ("testUnparsebleDraftIsStillConsideredDraft", testUnparsebleDraftIsStillConsideredDraft),
    ]
}

extension FileLocationTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__FileLocationTests = [
        ("testNoExtension", testNoExtension),
        ("testPage", testPage),
        ("testPageInFolder", testPageInFolder),
        ("testUnsupported", testUnsupported),
    ]
}

extension InputFileLoaderTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__InputFileLoaderTests = [
        ("testBasics", testBasics),
        ("testEmptyFrontMatter", testEmptyFrontMatter),
    ]
}

extension InputFileTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__InputFileTests = [
        ("testBasics", testBasics),
        ("testEmptyFrontMatter", testEmptyFrontMatter),
    ]
}

extension WebsiteTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__WebsiteTests = [
        ("testBasics", testBasics),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(DateFromPathTests.__allTests__DateFromPathTests),
        testCase(DatePathFragmentTests.__allTests__DatePathFragmentTests),
        testCase(DatePrefixTests.__allTests__DatePrefixTests),
        testCase(DraftTests.__allTests__DraftTests),
        testCase(FileLocationTests.__allTests__FileLocationTests),
        testCase(InputFileLoaderTests.__allTests__InputFileLoaderTests),
        testCase(InputFileTests.__allTests__InputFileTests),
        testCase(WebsiteTests.__allTests__WebsiteTests),
    ]
}
#endif
