#if !canImport(ObjectiveC)
import XCTest

extension StringTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__StringTests = [
        ("testDatePrefix", testDatePrefix),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(StringTests.__allTests__StringTests),
    ]
}
#endif
