name: ci

on:
  push:
    branches:
      - '**'
    tags:
      - '*.*.*'
  pull_request:
    

jobs:
  main:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: danramteke/leaf-press 
          tag-sha: true 
          tag-semver: true
      -
        name: Echo tags
        run: echo "${{ steps.docker_meta.outputs.tags }}"

      - name: Install rsync
        run: sudo apt-get install rsync

      - uses: fwal/setup-swift@v1
      - name: Get swift version
        run: swift --version 

      - 
        name: Test
        run: swift test
      - 
        name: Build Release
        run: swift build -c release

      - 
        name: Release Info
        id: release_info
        run: |
          echo "::set-output name=BIN_PATH::$(swift build -c release --show-bin-path)/leaf-press"
          if [ "main" == "$GITHUB_REF" ]; then
            CI_COMMIT_REF_NAME="sha-$GITHUB_SHA"
          else 
            CI_COMMIT_REF_NAME="$GITHUB_REF"
          fi
          echo "::set-output name=RELEASE_NAME::$CI_COMMIT_REF_NAME"

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: leaf-press-${{ steps.release_info.outputs.RELEASE_NAME }}-${{ matrix.os }}
          path: ${{ steps.release_info.outputs.BIN_PATH }}
      - name: Archive Test Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Test Artifacts ${{ matrix.os }}
          path: /tmp/leaf-press/Tests     
