name: ci

on: [push]
    

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Run Test
        id: docker_test
        uses: docker/build-push-action@v2
        with:
          push: false
          target: test
      -
        name: Build release image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: danramteke/leaf-press
          push: true
          tag_with_ref: true
          target: release
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}