name: ci

on:
  push:
    branches: '**'
    pull_request:

jobs:
  once:
    name: Create single release for all builds
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Create a release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
  main:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    needs: once
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2

      - name: Install rsync apt-get
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: sudo apt-get install rsync

      - name: Brew install rsync
        if: ${{ matrix.os == 'macos-latest' }}
        run: brew install rsync

      - uses: fwal/setup-swift@v1
      - name: Get swift version
        run: swift --version 

      - 
        name: Test
        if: startsWith( github.ref, 'refs/tags/releases/') != true
        run: swift test
      - 
        name: Build Release
        run: swift build -c release

      - 
        name: Release Info
        id: release_info
        run: |
          echo "::set-output name=BIN_PATH::$(swift build -c release --show-bin-path)/leaf-press"

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: leaf-press-${{ matrix.os }}
          path: ${{ steps.release_info.outputs.BIN_PATH }}
      - name: Archive Test Artifacts
        uses: actions/upload-artifact@v2
        if: startsWith( github.ref, 'refs/tags/releases/') != true
        with:
          name: Test Artifacts ${{ matrix.os }}
          path: /tmp/TestOutput     

      - name: Upload Release Asset
        id: upload-release-asset 
        if: startsWith( github.ref, 'refs/tags/releases/')
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ steps.release_info.outputs.BIN_PATH }}
          asset_name: leaf-press-${{ matrix.os }}
          asset_content_type: application/octet-stream