name: Release

on:
  push:
    tags: "[0-9]+.[0-9]+.[0-9]+"

jobs:
  create_github_release:
    name: Create single release for all builds
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Create a release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

  build:
    name: Build Release for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    needs: create_github_release
    strategy:
      matrix:
        include:
          - os: macos-11.0
            BUILD_CMD: swift build -c release
          - os: macos-10.15
            BUILD_CMD: swift build -c release
          - os: ubuntu-20.04
            BUILD_CMD: swift build -c release -Xswiftc -static-executable 

    steps:
      - uses: actions/checkout@v2
      - uses: fwal/setup-swift@v1
      - 
        name: Swift version confirm
        run: swift --version 
      - 
        name: Version
        run: echo ${{ github.ref }} > Sources/leaf-press/version.txt
      - 
        name: Build
        run: "${{ matrix.BUILD_CMD }}"
      - 
        name: Package
        run: tar czf release.tgz -C $(${{ matrix.BUILD_CMD }} --show-bin-path) leaf-press
      - 
        name: Upload  
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_github_release.outputs.upload_url }}
          asset_path: release.tgz
          asset_name: leaf-press-${{ matrix.os }}.tgz
          asset_content_type: application/octet-stream