name: Tests

on:
  push:
    branches: '**'
    pull_request:

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    needs: once
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2

      - name: rsync install ubuntu
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: sudo apt-get install rsync

      - name: rsync install macos
        if: ${{ matrix.os == 'macos-latest' }}
        run: brew install rsync

      - uses: fwal/setup-swift@v1
      - name: Get swift version
        run: swift --version 

      - name: Tests 
        run: swift test

      - name: Test Artifacts Upload
        uses: actions/upload-artifact@v2
        with:
          name: Test Artifacts ${{ matrix.os }}
          path: /tmp/TestOutput     

