name: Test

on:
  push:
    branches: '**'
    pull_request:

jobs:
  build:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-11.0
            BUILD_CMD: swift build -c release
          - os: macos-10.15
            BUILD_CMD: swift build -c release
          - os: ubuntu-20.04
            BUILD_CMD: swift build -c release -Xswiftc -static-executable 
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2

      - uses: fwal/setup-swift@v1
      - name: Get swift version
        run: swift --version 

      - name: Confirm Build
        run: "${{ matrix.BUILD_CMD }}"
      - name: Confirm Build runs
        run: |
          $(${{ matrix.BUILD_CMD }} --show-bin-path)/leaf-press init -w /tmp/TestOutput/leaf-press-init-release
          $(${{ matrix.BUILD_CMD }} --show-bin-path)/leaf-press build -w /tmp/TestOutput/leaf-press-init-release

      - name: Test
        run: swift test

      - name: Test Init
        run: |
          swift run leaf-press init -w /tmp/TestOutput/leaf-press-init
          swift run leaf-press build -w /tmp/TestOutput/leaf-press-init

      - name: Test Artifacts Upload
        uses: actions/upload-artifact@v2
        with:
          name: Test Artifacts ${{ matrix.os }}
          path: /tmp/TestOutput     

